spring.application.name=wallet

#Database
#spring.datasource.url=jdbc:postgresql://localhost:5432/accountDB
#spring.datasource.username=myUser
#spring.datasource.password=user_password
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.ddl-auto=none

#Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

cache.expiry.in.mills=30000
lock.expiry.in.mills=3000